[package]
name = "thanos"
version = "0.1.0"
authors = ["Lord-sarcastic <adeoti.15.jude@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.13"
rand = "0.8.4"
uuid = { version = "0.8.2", features = ["v4"] }