[package]
name = "thanos"
version = "0.1.0"
authors = ["Lord-sarcastic <adeoti.15.jude@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.13"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }